/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import cdcbconflicttranslator.CSVWorker;
import java.io.IOException;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import jxl.write.WriteException;

/**
 *
 * @author njdbi
 */
public class cdcbJFrame extends javax.swing.JFrame {

    /**
     * Creates new form cdcbJFrame
     */
    public cdcbJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();
        InputFileName = new javax.swing.JTextField();
        OutputExcelName = new javax.swing.JTextField();
        InputButtonBrowse = new javax.swing.JButton();
        OutputExcelBrowse = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ConsoleScreen = new javax.swing.JScrollPane();
        ConsoleTextArea = new javax.swing.JTextArea();
        runButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        InputButtonBrowse.setText("Browse");
        InputButtonBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputButtonBrowseActionPerformed(evt);
            }
        });

        OutputExcelBrowse.setText("Browse");
        OutputExcelBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OutputExcelBrowseActionPerformed(evt);
            }
        });

        jLabel1.setText("Input CSV file");

        jLabel2.setText("Output Excel file");

        ConsoleTextArea.setColumns(20);
        ConsoleTextArea.setRows(5);
        ConsoleScreen.setViewportView(ConsoleTextArea);

        runButton.setText("Run");
        runButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ConsoleScreen, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(InputFileName, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                    .addComponent(OutputExcelName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(InputButtonBrowse)
                    .addComponent(OutputExcelBrowse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(runButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(runButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(InputFileName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1))
                            .addComponent(InputButtonBrowse))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(OutputExcelName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(OutputExcelBrowse)
                            .addComponent(jLabel2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ConsoleScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InputButtonBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputButtonBrowseActionPerformed
        int returnVal = fileChooser.showOpenDialog(this);
        if(returnVal == JFileChooser.APPROVE_OPTION){
            this.InputFileName.setText(fileChooser.getSelectedFile().getAbsolutePath());
        }else{
            System.out.println("Error accessing input file location! " + fileChooser.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_InputButtonBrowseActionPerformed

    private void runButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runButtonActionPerformed
        //Parity check for data entry
        boolean inputField = !this.InputFileName.getText().equals("");
        boolean outputField = !this.OutputExcelName.getText().equals("");
        
        JFrame dialogFrame = new JFrame("Message Box");
        
        // Check if mandatory fields are filled
        if(!inputField || !outputField){
            if(!inputField){
                JOptionPane.showMessageDialog(dialogFrame, "You must enter an input CSV file to process!");
            }else{
                JOptionPane.showMessageDialog(dialogFrame, "You must select an output xls file name!");
            }
        }
        Path inputCSV = Paths.get(this.InputFileName.getText());
        Path outputXLS = Paths.get(this.OutputExcelName.getText());
        
        // Check if csv file exists
        boolean FileExists = inputCSV.toFile().canRead();
        
        if(!FileExists){
            JOptionPane.showMessageDialog(dialogFrame, "Could not read input CSV file! Please check if the file is hidden or modified!");
        }
        
        // Parity should be good, lets try running the conversion
        int state = runConversion(inputCSV, outputXLS);
        
        if(state == 1){
            JOptionPane.showMessageDialog(dialogFrame, "Conversion Completed successfully.");
        }
    }//GEN-LAST:event_runButtonActionPerformed

    private void OutputExcelBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OutputExcelBrowseActionPerformed
        int returnVal = fileChooser.showOpenDialog(this);
        if(returnVal == JFileChooser.APPROVE_OPTION){
            String outputFileText = fileChooser.getSelectedFile().getAbsolutePath();
            Pattern xls = Pattern.compile(".+\\.xls$");
            Matcher m = xls.matcher(outputFileText);
            if(!m.find()){
                // Add xls to the end of the file if it is missing
                outputFileText += ".xls";
            }
            this.OutputExcelName.setText(outputFileText);
        }else{
            System.out.println("Error accessing output file location! " + fileChooser.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_OutputExcelBrowseActionPerformed

    
    private static int runConversion(Path input, Path output){
        JFrame dialogFrame = new JFrame("Error Box");
        CSVWorker worker = new CSVWorker(input, output);
        
        try{
            int state = worker.run();
            if(state == 0){
                JOptionPane.showMessageDialog(dialogFrame, "There was an error writing to excel! May have encountered unexpected field!");
            }
        } catch(IOException ex){
            JOptionPane.showMessageDialog(dialogFrame, "There was an error reading the input. Please check file properties.");
        } catch (WriteException ex) {
            JOptionPane.showMessageDialog(dialogFrame, "There was an error writing to excel! May have encountered unexpected field!");
        }
        return 1;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cdcbJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cdcbJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cdcbJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cdcbJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new cdcbJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ConsoleScreen;
    private javax.swing.JTextArea ConsoleTextArea;
    private javax.swing.JButton InputButtonBrowse;
    private javax.swing.JTextField InputFileName;
    private javax.swing.JButton OutputExcelBrowse;
    private javax.swing.JTextField OutputExcelName;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton runButton;
    // End of variables declaration//GEN-END:variables
}
